all: safeadd.exe safesubtract.exe safemultiply.exe safedivide.exe

safeadd.exe: safeadd.c safeint.o util.o
	gcc safeadd.c safeint.o util.o -o safeadd.exe

safesubtract.exe: safesubtract.c safeint.o util.o
	gcc safesubtract.c safeint.o util.o -o safesubtract.exe

safemultiply.exe: safemultiply.c safeint.o util.o
	gcc safemultiply.c safeint.o util.o -o safemultiply.exe

safedivide.exe: safedivide.c safeint.o util.o
	gcc safedivide.c safeint.o util.o -o safedivide.exe

safeint.o: safeint.c safeint.h
	gcc safeint.c -c -o safeint.o

util.o: util.c util.h
	gcc util.c -c -o util.o

clean:
	del *.exe *.o
